name: CI MLflow Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs: 
  mlflow_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install mlflow

      - name: Run Preprocessing with MLflow
        run: |
          mlflow run . -e main

      - name: Run Modelling with MLflow
        run: |
          mlflow run . -e modelling

      - name: Run Tuning with MLflow
        run: |
          mlflow run . -e tuning
