name: CI Preprocessing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs: 
  preprocess:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to access the code
      - name: Checkout Repo
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.2'  # Ganti ke versi 3.9

      # Install required dependencies
      - name: Install Dependencies
        run: |
          pip install --upgrade pip  # Pastikan pip terbaru
          pip install -r requirements.txt

      # Run the preprocessing script
      - name: Run Preprocessing
        working-directory: ./preprocessing
        run: |
          python automate_Labiba-Adinda-Zahwana.py
